AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  MyAlbDnsName:
    Type: String


Resources:

  MyDistribution:
    Type: AWS::CloudFront::Distribution 
    Properties:
      DistributionConfig:
        Enabled: true 
        Origins: 
          - Id: AlbOrigin
            DomainName: !Ref MyAlbDnsName
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: AlbOrigin
          ViewerProtocolPolicy: allow-all 
          AllowedMethods:
            - GET 
            - HEAD
          CachedMethods:
            - GET 
            - HEAD 
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
