AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  S3BaseUrl:
    Type: String
    Description: "Base URL for S3 Bucket (https://my-bucket.s3.amazonaws.com/stacks/)"

  MyAmiId:
    Type: String
    Description: AMI ID for Instances


Resources:

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BaseUrl}network.yaml"

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BaseUrl}securitygroup.yaml"
      Parameters: 
        MyVpcId: !GetAtt NetworkStack.Outputs.VpcId

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BaseUrl}loadbalancer.yaml"
      Parameters:
        MyVpcId: !GetAtt NetworkStack.Outputs.VpcId
        MyPublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        MyPublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        MyAlbSgId: !GetAtt SecurityGroupStack.Outputs.AlbSgId

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BaseUrl}compute.yaml"
      Parameters:
        MyPrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        MyPrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        MyTargetGroupArn: !GetAtt LoadBalancerStack.Outputs.TargetGroupArn
        MyEc2SgId: !GetAtt SecurityGroupStack.Outputs.Ec2SgId
        MyAmiId: !Ref MyAmiId

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3BaseUrl}cloudfront.yaml"
      Parameters:
        MyAlbDnsName: !GetAtt LoadBalancerStack.Outputs.AlbDnsName
