AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  NetworkStackS3URL:
    Type: String

  SecurityGroupStackS3URL:
    Type: String

  LoadBalancerStackS3URL:
    Type: String

  ComputeStackS3URL:
    Type: String

  CloudFrontStackS3URL:
    Type: String


Resources:

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NetworkStackS3URL

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupStackS3URL
      Parameters: 
        MyVpcId: !GetAtt NetworkStack.Outputs.VpcId

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LoadBalancerStackS3URL
      Parameters:
        MyVpcId: !GetAtt NetworkStack.Outputs.VpcId
        MyPublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        MyPublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        MyAlbSgId: !GetAtt SecurityGroupStack.Outputs.AlbSgId

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ComputeStackS3URL
      Parameters:
        MyPrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        MyPrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        MyTargetGroupArn: !GetAtt LoadBalancerStack.Outputs.TargetGroupArn
        MyEc2SgId: !GetAtt SecurityGroupStack.Outputs.Ec2SgId

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref CloudFrontStackS3URL
      Parameters:
        MyAlbDnsName: !GetAtt LoadBalancerStack.Outputs.AlbDnsName
